package Presentacion;

import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

import Presentacion.biblioteca.JPanelBiblioteca;
import Presentacion.usuario.JPanelUsuarios;
import Presentacion.videojuego.JPanelVideojuego;

/**
 *
 * @author usuario_local
 */
public class MainWindow extends javax.swing.JFrame {
    private javax.swing.JPanel jPanel4;
    private JPanelBiblioteca jPanelBibliotecas;
    private JPanelUsuarios jPanelUsuarios;
    private JPanelVideojuego jPanelVideojuego;
    private JTabbedPane panelCambiante;

    // End of variables declaration
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        panelCambiante = new javax.swing.JTabbedPane();
        jPanelVideojuego = new JPanelVideojuego();
        jPanelUsuarios = new JPanelUsuarios();
        jPanelBibliotecas = new JPanelBiblioteca();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SpielBox");

        jPanel4.setBackground(new java.awt.Color(34, 88, 154));

        panelCambiante.setBackground(new java.awt.Color(255, 255, 255));

        jPanelVideojuego.setBackground(new java.awt.Color(255, 255, 255));

        panelCambiante.addTab("Videojuegos", jPanelVideojuego);

        jPanelUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        panelCambiante.addTab("Usuarios", jPanelUsuarios);

        jPanelBibliotecas.setBackground(new java.awt.Color(255, 255, 255));

        panelCambiante.addTab("Bibliotecas", jPanelBibliotecas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCambiante)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCambiante)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        //Configuramos el primer tabbed, el primer parámetro indica el índice.
        panelCambiante.setTitleAt(0, "Videojuego");
        panelCambiante.setIconAt(0, createImageIcon("images/videojuego.png"));
        panelCambiante.setToolTipTextAt(0, "Gestión Videojuego");
        //Configuramos el segundo tabbed, el primer parámetro indica el índice.
        panelCambiante.setTitleAt(1, "Usuarios");
        panelCambiante.setIconAt(1, createImageIcon("images/usuarios.png"));
        panelCambiante.setToolTipTextAt(1, "Gestión Usuarios");

        
        //Configuramos el tercer tabbed, el primer parámetro indica el índice.
        panelCambiante.setTitleAt(2, "Biblioteca");
        panelCambiante.setIconAt(2, createImageIcon("images/biblioteca.png"));
        panelCambiante.setToolTipTextAt(2, "Gestión Biblioteca"); 
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    
    }// </editor-fold>                                                                          

    //Método que nos permitirá cargar una imagen como icono pasándole una url
    private static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = MainWindow.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Archivo no encontrado: " + path);
            return null;
        }
    }
     
}
