package Presentacion;

import java.awt.Dimension;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

import Presentacion.biblioteca.JPanelBiblioteca;
import Presentacion.clasificacion.JPanelClasificacion;
import Presentacion.plataforma.JPanelPlataforma;
import Presentacion.programa.JPanelPrograma;
import Presentacion.usuario.JPanelUsuarios;
import Presentacion.videojuego.JPanelVideojuego;

/**
 *
 * @author usuario_local
 */
public class MainWindow extends javax.swing.JFrame {
    private javax.swing.JPanel jPanel4;
    ////////1ra parte ///////////////////////////
    private JPanelBiblioteca jPanelBibliotecas;
    private JPanelUsuarios jPanelUsuarios;
    private JPanelVideojuego jPanelVideojuego;
    
    ////////2da parte ///////////////////////////
    private JPanelPrograma jPanelPrograma;
    private JPanelPlataforma jPanelPlataforma;
    private JPanelClasificacion jPanelClasificacion;
    
    private JTabbedPane panelCambiante;

    // End of variables declaration
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        panelCambiante = new javax.swing.JTabbedPane();
        jPanelVideojuego = new JPanelVideojuego();
        jPanelUsuarios = new JPanelUsuarios();
        jPanelBibliotecas = new JPanelBiblioteca();
        //////2da parte///////
        jPanelClasificacion = new JPanelClasificacion();
        jPanelPrograma = new JPanelPrograma();
        jPanelPlataforma = new JPanelPlataforma();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SpielBox");

        jPanel4.setBackground(new java.awt.Color(34, 88, 154));

        panelCambiante.setBackground(new java.awt.Color(255, 255, 255));

        jPanelVideojuego.setBackground(new java.awt.Color(255, 255, 255));
        JPanel jp = new JPanel();
        JLabel labelSpielBox = new JLabel();
        labelSpielBox.setIcon(createImageIcon("images/SpieboxImage.png"));
        jp.add(labelSpielBox);
        //jp.add(createImageIcon("images/plataforma.png"));
        panelCambiante.addTab("Spielbox", jp);
        panelCambiante.addTab("Videojuegos", jPanelVideojuego);

        jPanelUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        panelCambiante.addTab("Usuarios", jPanelUsuarios);

        jPanelBibliotecas.setBackground(new java.awt.Color(255, 255, 255));

        panelCambiante.addTab("Bibliotecas", jPanelBibliotecas);
        
        /////////////////////////////////////////////////////////
        jPanelPrograma.setBackground(new java.awt.Color(255, 255, 255));
        panelCambiante.addTab("Programas",jPanelPrograma);
        
        jPanelClasificacion.setBackground(new java.awt.Color(255, 255, 255));
        panelCambiante.addTab("Clasificaciones",jPanelClasificacion);
        
        jPanelPlataforma.setBackground(new java.awt.Color(255, 255, 255));
        panelCambiante.addTab("Plataformas",jPanelPlataforma);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCambiante)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCambiante)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        //Configuramos el primer tabbed, el primer parámetro indica el índice.
        panelCambiante.setTitleAt(0, "SpielBox");
        panelCambiante.setIconAt(0, createImageIcon("images/spielbox-icon.png"));
        panelCambiante.setToolTipTextAt(0, "SpielBox");
        
        //Configuramos el primer tabbed, el primer parámetro indica el índice.
        panelCambiante.setTitleAt(1, "Videojuego");
        panelCambiante.setIconAt(1, createImageIcon("images/videojuego.png"));
        panelCambiante.setToolTipTextAt(1, "Gestión Videojuego");
        //Configuramos el segundo tabbed, el primer parámetro indica el índice.
        panelCambiante.setTitleAt(2, "Usuarios");
        panelCambiante.setIconAt(2, createImageIcon("images/usuarios.png"));
        panelCambiante.setToolTipTextAt(2, "Gestión Usuarios");

        
        //Configuramos el tercer tabbed, el primer parámetro indica el índice.
        panelCambiante.setTitleAt(3, "Biblioteca");
        panelCambiante.setIconAt(3, createImageIcon("images/biblioteca.png"));
        panelCambiante.setToolTipTextAt(3, "Gestión Biblioteca"); 
        
  ///////////////////////2DA PARTE /////////////////////////////////////////////////////      
        
        //Configuramos el 4to tabbed, el primer parámetro indica el índice.
        panelCambiante.setIconAt(4, createImageIcon("images/programa.png"));
        panelCambiante.setToolTipTextAt(4, "Gestión Programas"); 
        
        //Configuramos el 5to tabbed, el primer parámetro indica el índice.
        panelCambiante.setIconAt(5, createImageIcon("images/clasificacion.png"));
        panelCambiante.setToolTipTextAt(5, "Gestión Clasificaciones"); 
        
        //Configuramos el 6to tabbed, el primer parámetro indica el índice.
        panelCambiante.setIconAt(6, createImageIcon("images/plataforma.png"));
        panelCambiante.setToolTipTextAt(6, "Gestión Plataformas"); 
        
        this.setMinimumSize(new Dimension(1024, 700)); 
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    
    }// </editor-fold>                                                                          

    //Método que nos permitirá cargar una imagen como icono pasándole una url
    private static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = MainWindow.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Archivo no encontrado: " + path);
            return null;
        }
    }
     
}
